### ISSUE TITLE
Is there support for MPEGTS with UltraLowLatency mode

### ISSUE THREAD

**Issue by abhang-atish** [bluenviron/gohlslib#101]
According to specs [LINK](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-3.2) partial segments can be one of the Supported Media Segment Formats described in [Section 3.1](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-3.1). 

But when `MuxerVariantLowLatency` is used it generates fmp4

**Comment by aler9** [comment]
Hello, although the specification doesn't forbid using MPEG-TS with low-latency mode, no player supports this combination, therefore implementing it would be useless.
