### ISSUE TITLE
fmp4 Processor Error

### ISSUE THREAD

**Issue by t3pmd** [bluenviron/gohlslib#117]
can someone help please this is an error in the client_processor_fmp4.go file 

cannot use initFile (variable of type []byte) as io.ReadSeeker value in argument to p.init.Unmarshal: []byte does not implement io.ReadSeeker (missing method Read)

im a bit confused why as the Unmarshal is a byte type right?

hope someone could help

**Comment by aler9** [comment]
hello, make sure you're using the latest version of mediacommon and gohlslib.
