### ISSUE TITLE
Example client-codec-h264-save-to-disk panics

### ISSUE THREAD

**Issue by magicbic** [bluenviron/gohlslib#174]
Hello! I have been trying to use the example which reads from a HLS stream and saves the output to a .TS file, but unfortunately the example code panics. Here are the output from my console:

2024/09/04 12:35:42 downloading primary playlist http://redacted.com/video/stream.m3u8
2024/09/04 12:35:43 downloading segment http://redacted.com/video/24481
2024/09/04 12:35:45 downloading stream playlist http://redacted.com/video/stream.m3u8
panic: astits: fetching next packet failed: astits: fetching next packet from buffer failed: astits: building packet failed: astits: packet must start with a sync byte

goroutine 1 [running]:
main.main()
        /gohlslib/video/main.go:73 +0xdc
exit status 2

This HLS contains .mp4 files. I tried using this with mediamtx and the logs also reports the same problem. What could possibly be the problem to panic the code?

**Comment by aler9** [comment]
Hello, the problem is inside the content of your original stream, which we cannot analyze since it is not public. Open an issue in MediaMTX and provide a network dump and/or the public URL of the source.
